Lesson6
dzmrudak/Java_Lessons pull request #4
Opened 2021-02-22 18:23 UTC by dzmrudak

2021-02-23 14:04 UTC, AntonShtabnoy requested changes

2021-02-23 14:04 UTC, AntonShtabnoy commented on src/by/rudakd/lesson6/ArrayService.java
> +    public static int arrayLength = 10;
излишнее полу - длину массива ты всегда можешь получить из поля array

2021-02-23 14:04 UTC, AntonShtabnoy commented on src/by/rudakd/lesson6/ArrayService.java
> +        return null;
просто можно return array[i] и проверкой index > array.lenth

2021-02-23 14:04 UTC, AntonShtabnoy commented on src/by/rudakd/lesson6/ArrayService.java
> +        array = deletedArray;
просто можно array = new Integer[0]

2021-02-23 14:04 UTC, AntonShtabnoy commented on src/by/rudakd/lesson6/ArrayService.java
> +        return arrayOfIntegers;
здесь не должно быть ничего кроме заполнения данных - этот метод просто возвращает содержимое массива

2021-02-23 14:04 UTC, AntonShtabnoy commented on src/by/rudakd/lesson6/ArrayService.java
> +    int[] array;
Где конструкторы, которые инициализируют поле массив?

2021-02-27 12:32 UTC, dzmrudak commented on src/by/rudakd/lesson6/ArrayService.java
> +        return null;
Пока не посмотрел решение из лекции, ничего не понял.
Правильно было написать "просто можно return array[index] и перед этим сделать проверку на вхождение индекса в массив через index > array.lenth"

2021-02-27 12:32 UTC, dzmrudak commented on src/by/rudakd/lesson6/ArrayService.java
> +        array = deletedArray;
Поправил

2021-02-27 13:08 UTC, dzmrudak commented on src/by/rudakd/lesson6/ArrayService.java
> +    int[] array;
Добавил

2021-02-27 13:09 UTC, dzmrudak commented on src/by/rudakd/lesson6/ArrayService.java
> +        return arrayOfIntegers;
Поправил

2021-02-27 13:09 UTC, dzmrudak commented on src/by/rudakd/lesson6/ArrayService.java
> +    public static int arrayLength = 10;
Поправил

2021-02-28 22:54 UTC, merged